// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv36y4DqArGJSMTbZ98Oh1UGthyYm8h7U',
    appId: '1:128872534940:web:fd5e305816848f26966e59',
    messagingSenderId: '128872534940',
    projectId: 'mentalzen-3c152',
    authDomain: 'mentalzen-3c152.firebaseapp.com',
    storageBucket: 'mentalzen-3c152.firebasestorage.app',
    measurementId: 'G-QREF7HZYRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgP1atbXDM3puAn-NOtT4aRJaZhVss7qk',
    appId: '1:128872534940:android:10521ad12356da53966e59',
    messagingSenderId: '128872534940',
    projectId: 'mentalzen-3c152',
    storageBucket: 'mentalzen-3c152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVf4BIVRLE6jPdcddFH2NQb_Mwafksce4',
    appId: '1:128872534940:ios:73a7cc8d7fcb16a9966e59',
    messagingSenderId: '128872534940',
    projectId: 'mentalzen-3c152',
    storageBucket: 'mentalzen-3c152.firebasestorage.app',
    iosBundleId: 'com.example.mentalZen1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVf4BIVRLE6jPdcddFH2NQb_Mwafksce4',
    appId: '1:128872534940:ios:73a7cc8d7fcb16a9966e59',
    messagingSenderId: '128872534940',
    projectId: 'mentalzen-3c152',
    storageBucket: 'mentalzen-3c152.firebasestorage.app',
    iosBundleId: 'com.example.mentalZen1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv36y4DqArGJSMTbZ98Oh1UGthyYm8h7U',
    appId: '1:128872534940:web:9cb53461558d7a3a966e59',
    messagingSenderId: '128872534940',
    projectId: 'mentalzen-3c152',
    authDomain: 'mentalzen-3c152.firebaseapp.com',
    storageBucket: 'mentalzen-3c152.firebasestorage.app',
    measurementId: 'G-NHSBF4B3VF',
  );

}